"""Add macro columns to WorkoutModel

Revision ID: b649870cc912
Revises: 4e46de44ecfa
Create Date: 2024-12-19 14:36:57.255958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b649870cc912'
down_revision = '4e46de44ecfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('carbs')

    # ### end Alembic commands ###
